/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import opcionesadministrativas.*;
/**
 *
 * @author Warner Diaz
 */
public class AlquilerVehiculos extends javax.swing.JFrame {
    Registro registro;
    ValoresDeInicio factura;
    Facturas generarFactura;
    /**
     * Creates new form AlquilerVehiculos
     */
    public AlquilerVehiculos() throws Exception{
        initComponents();
        this.setSize(530,340);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        registro = new Registro();
        factura = new ValoresDeInicio();
        generarFactura = new Facturas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAlquiler = new javax.swing.JLabel();
        jLabelPlaca = new javax.swing.JLabel();
        jLabelHoras = new javax.swing.JLabel();
        jTextFieldPlaca = new javax.swing.JTextField();
        jTextFieldHoras = new javax.swing.JTextField();
        jButtonAlquilar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAlquiler.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabelAlquiler.setText("Alquiler de Vehiculos");
        getContentPane().add(jLabelAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 220, 38));

        jLabelPlaca.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelPlaca.setText("Placa");
        getContentPane().add(jLabelPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 100, 31));

        jLabelHoras.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelHoras.setText("Horas");
        getContentPane().add(jLabelHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 100, 40));

        jTextFieldPlaca.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jTextFieldPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 140, 40));

        jTextFieldHoras.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        getContentPane().add(jTextFieldHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 140, 40));

        jButtonAlquilar.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonAlquilar.setText("Alquilar");
        jButtonAlquilar.setBorderPainted(false);
        jButtonAlquilar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAlquilar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAlquilarMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonAlquilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 170, 40));

        jButtonAtras.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonAtras.setText("Atrás");
        jButtonAtras.setBorderPainted(false);
        jButtonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 170, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtrasMouseClicked
        this.setVisible(false);
        OpcionesGenerales ventana = new OpcionesGenerales();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonAtrasMouseClicked

    private void jButtonAlquilarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAlquilarMouseClicked
        String placa = jTextFieldPlaca.getText();
        String horas = jTextFieldHoras.getText();   
        try{
            Integer.parseInt(horas);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Introduzca horas válidas");
            return;
        }
        if (Integer.parseInt(horas) > 1){
            if(horas.length() > 0 && horas.length() > 0){
                try {
                    int respuesta = registro.alquilarVehiculo(placa, horas);
                    if (respuesta > 0){
                        factura.setFactura();
                        JOptionPane.showMessageDialog(null, generarFactura.getFactura(placa, horas));
                    }
                    else if(respuesta == 0){
                        JOptionPane.showMessageDialog(null, "No se encuentra este auto");
                    }
                    else JOptionPane.showMessageDialog(null,"Este auto se encuentra alquilado");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"Introduzca horas válidas");
                    Logger.getLogger(AlquilerVehiculos.class.getName()).log(Level.SEVERE, null, e);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "No puede dejar espacion en blanco");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Se acepta alquiler de dos horas en adelante");
        }
        
    }//GEN-LAST:event_jButtonAlquilarMouseClicked

    private void jTextFieldPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlquilerVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlquilerVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlquilerVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlquilerVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AlquilerVehiculos().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(AlquilerVehiculos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlquilar;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JLabel jLabelAlquiler;
    private javax.swing.JLabel jLabelHoras;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JTextField jTextFieldHoras;
    private javax.swing.JTextField jTextFieldPlaca;
    // End of variables declaration//GEN-END:variables
}
