/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica;

import javax.swing.JOptionPane;
import opcionesadministrativas.ValoresDeInicio;
/**
 *
 * @author Warner Diaz
 */
public class CambiarContrasena extends javax.swing.JFrame {
     ValoresDeInicio valores;
    /**
     * Creates new form CambiarContrasena
     */
    public CambiarContrasena() {
        initComponents();
        this.setResizable(false);
        this.setSize(400,300);
        this.setLocationRelativeTo(null);
        valores = new ValoresDeInicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAnterior = new javax.swing.JLabel();
        jLabelNueva = new javax.swing.JLabel();
        jButtonCambiar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jPasswordFieldAnterior = new javax.swing.JPasswordField();
        jPasswordFieldNueva = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAnterior.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelAnterior.setText("Contraseña Anterior");
        getContentPane().add(jLabelAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 30));

        jLabelNueva.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelNueva.setText("Nueva Contraseña");
        getContentPane().add(jLabelNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, 30));

        jButtonCambiar.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonCambiar.setText("Cambiar");
        jButtonCambiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCambiar.setBorderPainted(false);
        jButtonCambiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCambiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambiarMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 130, 40));

        jButtonAtras.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonAtras.setText("Atrás");
        jButtonAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAtras.setBorderPainted(false);
        jButtonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 130, 40));

        jPasswordFieldAnterior.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        getContentPane().add(jPasswordFieldAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 150, 40));

        jPasswordFieldNueva.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        getContentPane().add(jPasswordFieldNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 150, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtrasMouseClicked
        this.setVisible(false);
        ValoresIniciales ventana = new ValoresIniciales();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonAtrasMouseClicked

    private void jButtonCambiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambiarMouseClicked
        String antiguaContrasena = jPasswordFieldAnterior.getText();
        String nuevaContrasena = jPasswordFieldNueva.getText();
        if (antiguaContrasena.length() > 0 && nuevaContrasena.length() > 0){
            int respuesta = valores.setContrasena(antiguaContrasena, nuevaContrasena);
            if (respuesta > 0){
                JOptionPane.showMessageDialog(null, "Se cambio la contraseña con éxito");
            }
            else{
                JOptionPane.showMessageDialog(null, "Contraseña invalida");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "No puede dejar espacion en blanco");
        }
            
    }//GEN-LAST:event_jButtonCambiarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarContrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonCambiar;
    private javax.swing.JLabel jLabelAnterior;
    private javax.swing.JLabel jLabelNueva;
    private javax.swing.JPasswordField jPasswordFieldAnterior;
    private javax.swing.JPasswordField jPasswordFieldNueva;
    // End of variables declaration//GEN-END:variables
}
