/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import opcionesadministrativas.Registro;
/**
 *
 * @author Warner Diaz
 */
public class ConsultaVehiculos extends javax.swing.JFrame {
        Registro registro;
    /**
     * Creates new form ConsultaVehiculos
     */
    public ConsultaVehiculos() {
        initComponents();
        this.setSize(980,540);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
            try {
                registro = new Registro();
            } catch (Exception ex) {
                Logger.getLogger(ConsultaVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jTextArea.setText(registro.consultaVehiculos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxEstado = new javax.swing.JComboBox<>();
        jButtonFiltrar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jLabelMarca = new javax.swing.JLabel();
        jLabelConsulta = new javax.swing.JLabel();
        jLabelPlaca = new javax.swing.JLabel();
        jLabelFiltrar = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabelBusMarca = new javax.swing.JLabel();
        jLabelAnno = new javax.swing.JLabel();
        jLabelBusTipo = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelBusEstado = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldTipo = new javax.swing.JTextField();
        jButtonAlquilar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxEstado.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "Alquilado" }));
        getContentPane().add(jComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, 30));

        jButtonFiltrar.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonFiltrar.setText("Filtrar");
        jButtonFiltrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonFiltrar.setBorderPainted(false);
        jButtonFiltrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFiltrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFiltrarMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 150, 40));

        jButtonAtras.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonAtras.setText("Atrás");
        jButtonAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAtras.setBorderPainted(false);
        jButtonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 150, 40));

        jLabelMarca.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelMarca.setText("Marca");
        getContentPane().add(jLabelMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 60, 30));

        jLabelConsulta.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabelConsulta.setText("Consulta de Vehículos");
        getContentPane().add(jLabelConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 220, 40));

        jLabelPlaca.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelPlaca.setText("Placa");
        getContentPane().add(jLabelPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 70, 30));

        jLabelFiltrar.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelFiltrar.setText("Filtrar por:");
        getContentPane().add(jLabelFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 100, 29));

        jLabelModelo.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelModelo.setText("Modelo");
        getContentPane().add(jLabelModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 50, 30));

        jLabelBusMarca.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelBusMarca.setText("Marca:");
        getContentPane().add(jLabelBusMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 90, 30));

        jLabelAnno.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelAnno.setText("Año");
        getContentPane().add(jLabelAnno, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 60, 30));

        jLabelBusTipo.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelBusTipo.setText("Tipo:");
        getContentPane().add(jLabelBusTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 80, 30));

        jLabelTipo.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelTipo.setText("Tipo");
        getContentPane().add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 60, 30));

        jLabelBusEstado.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelBusEstado.setText("Estado:");
        getContentPane().add(jLabelBusEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 80, 30));

        jLabelEstado.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelEstado.setText("Estado");
        getContentPane().add(jLabelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 50, 30));

        jTextArea.setColumns(20);
        jTextArea.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jTextArea.setRows(5);
        jTextArea.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 657, 269));
        getContentPane().add(jTextFieldMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 100, 30));

        jTextFieldTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 100, 32));

        jButtonAlquilar.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonAlquilar.setText("Alquilar");
        jButtonAlquilar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAlquilar.setBorderPainted(false);
        jButtonAlquilar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAlquilar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAlquilarMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonAlquilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 150, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtrasMouseClicked
        this.setVisible(false);
        OpcionesGenerales ventana = new OpcionesGenerales();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonAtrasMouseClicked

    private void jTextFieldTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoActionPerformed

    private void jButtonFiltrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFiltrarMouseClicked
        String marca, tipo , estado;
        marca = jTextFieldMarca.getText();
        tipo = jTextFieldTipo.getText();
        estado = jComboBoxEstado.getSelectedItem().toString();
        System.out.println(estado);
        String resultado = "";
        if(marca.length() > 0 && tipo.length() > 0){
            resultado += registro.consultaGlobal(marca,tipo,estado);
        }
        else if(marca.length() > 0 && tipo.length() == 0 ){
            resultado += registro.consultaMarca(marca, estado);
        }
        else if(marca.length() == 0 && tipo.length() > 0 ){
            resultado += registro.consultaTipo(tipo, estado);
        }
        else {
            resultado += registro.consultaEstado(estado);
        }
        System.out.println("REsd: " + resultado);
        if(resultado.length() > 0){
            this.jTextArea.setText(resultado);
            //this.jTextArea.setText(resultado);
        }
        else{
            this.jTextArea.setText("");
            JOptionPane.showMessageDialog(null, "No hay resultados de busqueda");
        }
    }//GEN-LAST:event_jButtonFiltrarMouseClicked

    private void jButtonAlquilarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAlquilarMouseClicked
        this.setVisible(false);
        AlquilerVehiculos ventana;
            try {
                ventana = new AlquilerVehiculos();
                ventana.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(ConsultaVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButtonAlquilarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaVehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlquilar;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JLabel jLabelAnno;
    private javax.swing.JLabel jLabelBusEstado;
    private javax.swing.JLabel jLabelBusMarca;
    private javax.swing.JLabel jLabelBusTipo;
    private javax.swing.JLabel jLabelConsulta;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelFiltrar;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables
}
