/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import opcionesadministrativas.Registro;
/**
 *
 * @author Warner Diaz
 */
public class DevolverVehiculos extends javax.swing.JFrame {
    
    Registro registro;
    /**
     * Creates new form DevolverVehiculo
     */
    public DevolverVehiculos() throws Exception {
        initComponents();
        this.setSize(400,300);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        registro = new Registro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDevolver = new javax.swing.JLabel();
        jLabelPlaca = new javax.swing.JLabel();
        jTextFieldPlaca = new javax.swing.JTextField();
        jButtonDevolver = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDevolver.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabelDevolver.setText("Devolución de  Vehiculos");
        getContentPane().add(jLabelDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 30));

        jLabelPlaca.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelPlaca.setText("Placa:");
        getContentPane().add(jLabelPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 60, 30));

        jTextFieldPlaca.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        getContentPane().add(jTextFieldPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 140, 30));

        jButtonDevolver.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonDevolver.setText("Devolver");
        jButtonDevolver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDevolver.setBorderPainted(false);
        jButtonDevolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDevolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDevolverMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 130, 40));

        jButtonAtras.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonAtras.setText("Atrás");
        jButtonAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAtras.setBorderPainted(false);
        jButtonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtrasMouseClicked
        this.setVisible(false);
        OpcionesGenerales ventana = new OpcionesGenerales();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonAtrasMouseClicked

    private void jButtonDevolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDevolverMouseClicked
        String placa = jTextFieldPlaca.getText();
        if(placa.length() > 0){
            try {
                int respuesta = registro.devolverVehiculo(placa);
                if (respuesta > 0)
                    JOptionPane.showMessageDialog(null ,"Se devolvio el vehiculo");
                else JOptionPane.showMessageDialog(null,"El auto no se encuentra alquilado");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al devolver el vehiculo");
                Logger.getLogger(DevolverVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"No puede dejar espacios en blanco");
        }
    }//GEN-LAST:event_jButtonDevolverMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DevolverVehiculos().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(DevolverVehiculos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonDevolver;
    private javax.swing.JLabel jLabelDevolver;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JTextField jTextFieldPlaca;
    // End of variables declaration//GEN-END:variables
}
