/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica;

import opcionesadministrativas.Facturas;
/**
 *
 * @author Warner Diaz
 */
public class HistorialDeAlquileres extends javax.swing.JFrame {
    Facturas facturas;
    /**
     * Creates new form HistorialDeAlquileres
     */
    public HistorialDeAlquileres() {
        initComponents();
        this.setSize(945,520);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        facturas = new Facturas();
        this.jTextAreaFacturas.setText(facturas.getFacturas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHistorial = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaFacturas = new javax.swing.JTextArea();
        jButtonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHistorial.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabelHistorial.setText("Historial de Alquileres");
        getContentPane().add(jLabelHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 23, 230, 31));

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabel1.setText("Identificador");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 89, 30));

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabel2.setText("Fecha y Hora");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 96, 30));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabel3.setText("Horas de Alquiler");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, 30));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabel4.setText("Placa");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 45, 30));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabel5.setText("Marca");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 50, 30));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabel6.setText("Tipo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 36, 30));

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabel7.setText("Monto Total");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, -1, 30));

        jTextAreaFacturas.setColumns(20);
        jTextAreaFacturas.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jTextAreaFacturas.setRows(5);
        jTextAreaFacturas.setFocusable(false);
        jScrollPane1.setViewportView(jTextAreaFacturas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 770, 301));

        jButtonAtras.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonAtras.setText("Atrás");
        jButtonAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAtras.setBorderPainted(false);
        jButtonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtrasMouseClicked
        this.setVisible(false);
        OpcionesAdministrativas ventana = new OpcionesAdministrativas();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonAtrasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialDeAlquileres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialDeAlquileres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialDeAlquileres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialDeAlquileres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistorialDeAlquileres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelHistorial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaFacturas;
    // End of variables declaration//GEN-END:variables
}
