/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Warner Diaz
 */
public class OpcionesAdministrativas extends javax.swing.JFrame {

    /**
     * Creates new form OpcionesAdministrativas
     */
    public OpcionesAdministrativas() {
        initComponents();
        this.setSize(625,392);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonValoresIniCiales = new javax.swing.JButton();
        jButtonRegTipVeh = new javax.swing.JButton();
        jButtonRegVeh = new javax.swing.JButton();
        jButtonHistAlquileres = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonValoresIniCiales.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonValoresIniCiales.setText("Valores Iniciales");
        jButtonValoresIniCiales.setBorderPainted(false);
        jButtonValoresIniCiales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonValoresIniCiales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonValoresIniCialesMouseClicked(evt);
            }
        });
        jButtonValoresIniCiales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValoresIniCialesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonValoresIniCiales, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 210, 40));

        jButtonRegTipVeh.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonRegTipVeh.setText("Registro de Tipo de Vehiculos");
        jButtonRegTipVeh.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRegTipVeh.setBorderPainted(false);
        jButtonRegTipVeh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegTipVeh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegTipVehMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonRegTipVeh, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 210, 40));

        jButtonRegVeh.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonRegVeh.setText("Registro de Vehiculos");
        jButtonRegVeh.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRegVeh.setBorderPainted(false);
        jButtonRegVeh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegVeh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegVehMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonRegVeh, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 210, 40));

        jButtonHistAlquileres.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonHistAlquileres.setText("Historial de Alquileres");
        jButtonHistAlquileres.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonHistAlquileres.setBorderPainted(false);
        jButtonHistAlquileres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHistAlquileres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHistAlquileresMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonHistAlquileres, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 210, 40));

        jButtonAtras.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonAtras.setText("Atrás");
        jButtonAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAtras.setBorderPainted(false);
        jButtonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 210, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValoresIniCialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonValoresIniCialesMouseClicked
        this.setVisible(false);
        ValoresIniciales ventana = new ValoresIniciales();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonValoresIniCialesMouseClicked

    private void jButtonRegTipVehMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegTipVehMouseClicked
        this.setVisible(false);
        RegistroTipoVehiculos ventana;
        try {
            ventana = new RegistroTipoVehiculos();
            ventana.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(OpcionesAdministrativas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRegTipVehMouseClicked

    private void jButtonRegVehMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegVehMouseClicked
        this.setVisible(false);
        RegistroVehiculos ventana;
        try {
            ventana = new RegistroVehiculos();
            ventana.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(OpcionesAdministrativas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRegVehMouseClicked

    private void jButtonHistAlquileresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHistAlquileresMouseClicked
        this.setVisible(false);
        HistorialDeAlquileres ventana = new HistorialDeAlquileres();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonHistAlquileresMouseClicked

    private void jButtonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtrasMouseClicked
        this.setVisible(false);
        Inicio ventana = new Inicio();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonAtrasMouseClicked

    private void jButtonValoresIniCialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValoresIniCialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonValoresIniCialesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesAdministrativas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesAdministrativas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesAdministrativas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesAdministrativas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesAdministrativas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonHistAlquileres;
    private javax.swing.JButton jButtonRegTipVeh;
    private javax.swing.JButton jButtonRegVeh;
    private javax.swing.JButton jButtonValoresIniCiales;
    // End of variables declaration//GEN-END:variables
}
