/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Warner Diaz
 */
public class OpcionesGenerales extends javax.swing.JFrame {

    /**
     * Creates new form OpcionesGenerales
     */
    public OpcionesGenerales() {
        initComponents();
        this.setSize(650,400);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConsulta = new javax.swing.JButton();
        jButtonAlquiler = new javax.swing.JButton();
        jButtonDevolver = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonConsulta.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonConsulta.setText("Consulta de Vehiculos");
        jButtonConsulta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonConsulta.setBorderPainted(false);
        jButtonConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConsultaMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 200, 50));

        jButtonAlquiler.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonAlquiler.setText("Alquiler de Vehiculos");
        jButtonAlquiler.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAlquiler.setBorderPainted(false);
        jButtonAlquiler.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAlquiler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAlquilerMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 200, 50));

        jButtonDevolver.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonDevolver.setText("Devolver Vehiculo");
        jButtonDevolver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDevolver.setBorderPainted(false);
        jButtonDevolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDevolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDevolverMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 200, 50));

        jButtonAtras.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonAtras.setText("Atrás");
        jButtonAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAtras.setBorderPainted(false);
        jButtonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 200, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsultaMouseClicked
        this.setVisible(false);
        ConsultaVehiculos ventana;
        try {
            ventana = new ConsultaVehiculos();
            ventana.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(OpcionesGenerales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonConsultaMouseClicked

    private void jButtonAlquilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAlquilerMouseClicked
        this.setVisible(false);
        AlquilerVehiculos ventana;
        try {
            ventana = new AlquilerVehiculos();
            ventana.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(OpcionesGenerales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAlquilerMouseClicked

    private void jButtonDevolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDevolverMouseClicked
        this.setVisible(false);
        DevolverVehiculos ventana;
        try {
            ventana = new DevolverVehiculos();
            ventana.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(OpcionesGenerales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonDevolverMouseClicked

    private void jButtonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtrasMouseClicked
        this.setVisible(false);
        Inicio ventana = new Inicio();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonAtrasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesGenerales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesGenerales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesGenerales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesGenerales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesGenerales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlquiler;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonConsulta;
    private javax.swing.JButton jButtonDevolver;
    // End of variables declaration//GEN-END:variables
}
