/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica;

import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import opcionesadministrativas.Registro;
/**
 *
 * @author Warner Diaz
 */
public class RegistroVehiculos extends javax.swing.JFrame {

    
    private Registro registro;
    /**
     * Creates new form RegistroVehiculos
     * @throws java.lang.Exception
     */
    
    public RegistroVehiculos() throws Exception {
        initComponents();
        this.setSize(805,435);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        registro = new Registro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRegVeh = new javax.swing.JLabel();
        jLabelPlaca = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabelAño = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jTextFieldPlaca = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldAnno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonEliminar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jTextFieldTipo = new javax.swing.JTextField();
        jTextFieldEliminar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRegVeh.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabelRegVeh.setText("Registrar Vehiculos");
        getContentPane().add(jLabelRegVeh, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 250, 32));

        jLabelPlaca.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelPlaca.setText("Placa:");
        getContentPane().add(jLabelPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 30));

        jLabelMarca.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelMarca.setText("Marca:");
        getContentPane().add(jLabelMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 90, 30));

        jLabelModelo.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelModelo.setText("Modelo:");
        getContentPane().add(jLabelModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 90, 30));

        jLabelAño.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelAño.setText("Año:");
        getContentPane().add(jLabelAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 90, 30));

        jLabelTipo.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelTipo.setText("Tipo:");
        getContentPane().add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 90, 30));

        jTextFieldPlaca.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        getContentPane().add(jTextFieldPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 160, 40));

        jTextFieldMarca.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        getContentPane().add(jTextFieldMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 160, 40));

        jTextFieldModelo.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        getContentPane().add(jTextFieldModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 160, 40));

        jTextFieldAnno.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        getContentPane().add(jTextFieldAnno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 160, 40));

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabel1.setText("Placa del Vehiculo a eliminar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, 27));

        jButtonEliminar.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEliminar.setBorderPainted(false);
        jButtonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEliminarMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 140, 30));

        jButtonAtras.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonAtras.setText("Atrás");
        jButtonAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAtras.setBorderPainted(false);
        jButtonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAtrasMouseClicked(evt);
            }
        });
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 140, 30));

        jButtonRegistrar.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRegistrar.setBorderPainted(false);
        jButtonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegistrarMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 140, 30));

        jTextFieldTipo.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jTextFieldTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 160, 40));

        jTextFieldEliminar.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        getContentPane().add(jTextFieldEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 105, 32));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtrasMouseClicked
        this.setVisible(false);
        OpcionesAdministrativas ventana = new OpcionesAdministrativas();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonAtrasMouseClicked

    private void jButtonRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegistrarMouseClicked
        String placa, marca, modelo, anno, tipo;
        placa = jTextFieldPlaca.getText();
        marca = jTextFieldMarca.getText();
        modelo = jTextFieldModelo.getText();
        anno = jTextFieldAnno.getText();
        tipo = jTextFieldTipo.getText();
        if(placa.length() > 0 && marca.length() > 0 && modelo.length() > 0 && anno.length() > 0 && tipo.length() > 0){
            try {
                int respuesta = registro.agregarVehiculo(placa, marca, modelo, anno, tipo);
                if (respuesta > 0)
                    JOptionPane.showMessageDialog(null, "Se registro el nuevo auto correctamente");
                else if (respuesta == 0)
                    JOptionPane.showMessageDialog(null,"El tipo no se encuentra agregado");
                else JOptionPane.showMessageDialog(null, "La placa ya se encuentre registrada");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al registrar el nuevo vehiculo");
                Logger.getLogger(RegistroVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "No puede dejar espacios en blanco");
        }
    }//GEN-LAST:event_jButtonRegistrarMouseClicked

    private void jButtonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarMouseClicked
        String placa = jTextFieldEliminar.getText();
        if(placa.length() > 0){
            try {
                int respuesta = registro.eliminarVehiculo(placa);
                if (respuesta > 0)
                    JOptionPane.showMessageDialog(null, "Eliminado con exito");
                else if(respuesta == 0)
                    JOptionPane.showMessageDialog(null, "No se encontró el auto");
                else JOptionPane.showMessageDialog(null, "El auto se encuentra alquilado");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al eliminar el auto");
                Logger.getLogger(RegistroVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "No puede dejar espacion en blanco");
        }
    }//GEN-LAST:event_jButtonEliminarMouseClicked

    private void jTextFieldTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RegistroVehiculos().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(RegistroVehiculos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAño;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelRegVeh;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JTextField jTextFieldAnno;
    private javax.swing.JTextField jTextFieldEliminar;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldPlaca;
    private javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables

}
