/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica;

import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import opcionesadministrativas.Registro;
/**
 *
 * @author Warner Diaz
 */
public class RegistroTipoVehiculos extends javax.swing.JFrame {

    Registro registro;
    /**
     * Creates new form RegistroTipoVehiculos
     */
    public RegistroTipoVehiculos() throws Exception{
        initComponents();
        this.setResizable(false);
        this.setSize(911,480);
        this.setLocationRelativeTo(null);
        registro = new Registro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNuevoRegistro = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelTarifa = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jTextFieldTipo = new javax.swing.JTextField();
        jTextFieldTarifa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonEliminar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jTextFieldEliminar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNuevoRegistro.setFont(new java.awt.Font("Century Schoolbook", 2, 18)); // NOI18N
        jLabelNuevoRegistro.setText("Registrar Nuevo Tipo de Vehículo");
        getContentPane().add(jLabelNuevoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 330, 50));

        jLabelTipo.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelTipo.setText("Tipo:");
        getContentPane().add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 56, 30));

        jLabelDescripcion.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelDescripcion.setText("Descripción:");
        getContentPane().add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 30));

        jLabelTarifa.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelTarifa.setText("Tarifa:");
        getContentPane().add(jLabelTarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 56, 40));

        jTextFieldDescripcion.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        getContentPane().add(jTextFieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 170, 40));

        jTextFieldTipo.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        getContentPane().add(jTextFieldTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 170, 40));

        jTextFieldTarifa.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        getContentPane().add(jTextFieldTarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 170, 40));

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabel1.setText("Eliminar Tipo de Vehículo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 210, 39));

        jButtonEliminar.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setActionCommand("");
        jButtonEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEliminar.setBorderPainted(false);
        jButtonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEliminarMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 130, 30));

        jButtonAtras.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonAtras.setText("Atrás");
        jButtonAtras.setActionCommand("");
        jButtonAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAtras.setBorderPainted(false);
        jButtonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 130, 30));

        jButtonRegistrar.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.setActionCommand("");
        jButtonRegistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRegistrar.setBorderPainted(false);
        jButtonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegistrarMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 130, 30));

        jTextFieldEliminar.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        getContentPane().add(jTextFieldEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 200, 32));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtrasMouseClicked
        this.setVisible(false);
        OpcionesAdministrativas ventana = new OpcionesAdministrativas();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonAtrasMouseClicked

    private void jButtonRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegistrarMouseClicked
        String descripcion, tipo, tarifa;
        descripcion = jTextFieldDescripcion.getText();
        tipo = jTextFieldTipo.getText();
        tarifa = jTextFieldTarifa.getText();
        if(descripcion.length() > 0 && tipo.length() > 0 && tarifa.length() > 0){
            try {
                int respuesta = registro.agregarTipoVehiculo(descripcion, tipo, tarifa);
                if (respuesta > 0)
                    JOptionPane.showMessageDialog(null, "Se registro el tipo "+ tipo + " correctamente");
                else JOptionPane.showMessageDialog(null, "No se puede registrar un mismo tipo con la misma descripcion");
            } catch (Exception ex) {
                Logger.getLogger(RegistroTipoVehiculos.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error al registrar el nuevo tipo de vehiculo");
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "No puede dejar espacios en blanco");
        }
    }//GEN-LAST:event_jButtonRegistrarMouseClicked

    private void jButtonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarMouseClicked
        String tipo = jTextFieldEliminar.getText();
        if(tipo.length() > 0){
            try {
                int respuesta = registro.eliminarTipoVehiculo(tipo);
                if (respuesta > 0)
                    JOptionPane.showMessageDialog(null,"Se elimino correctamente");
                else if(respuesta == 0)
                    JOptionPane.showMessageDialog(null,"No existe el tipo especificado");
                else JOptionPane.showMessageDialog(null,"Contiene autos, no se puede eliminar");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al eliminar el tipo de auto");
                Logger.getLogger(RegistroTipoVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "No puede dejar espacion en blanco");
        }
    }//GEN-LAST:event_jButtonEliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroTipoVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroTipoVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroTipoVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroTipoVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RegistroTipoVehiculos().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(RegistroTipoVehiculos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelNuevoRegistro;
    private javax.swing.JLabel jLabelTarifa;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldEliminar;
    private javax.swing.JTextField jTextFieldTarifa;
    private javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables
}
