/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica;

import javax.swing.JOptionPane;
import opcionesadministrativas.ValoresDeInicio;
/**
 *
 * @author Warner Diaz
 */
public class ValoresIniciales extends javax.swing.JFrame {
    ValoresDeInicio valores;
    /**
     * Creates new form ValoresIniciales
     */
    public ValoresIniciales() {
        initComponents();
        valores = new ValoresDeInicio();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setSize(921,452);
        this.jTextFieldNombreLocal.setText(valores.getNombre());
        this.jTextFieldEslogan.setText(valores.getEslogan());
        this.jTextFieldTelefono.setText(valores.getTelefono());
        this.jTextFieldCedulaJuridica.setText(valores.getCedulaJuridica());
        this.jTextFieldHorario.setText(valores.getHorario());
        this.jLabelContrasenaEncriptada.setText(valores.getContrasena());
        this.jLabelFactura.setText(String.valueOf(Integer.parseInt(valores.getFactura())+1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombreLocal = new javax.swing.JLabel();
        jLabelEslogan = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelCedulaJuridica = new javax.swing.JLabel();
        jLabelHorario = new javax.swing.JLabel();
        jLabelSiguienteFactura = new javax.swing.JLabel();
        jTextFieldNombreLocal = new javax.swing.JTextField();
        jTextFieldEslogan = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldCedulaJuridica = new javax.swing.JTextField();
        jTextFieldHorario = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jButtonContrasena = new javax.swing.JButton();
        jLabelContrasena = new javax.swing.JLabel();
        jLabelContrasenaEncriptada = new javax.swing.JLabel();
        jLabelFactura = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombreLocal.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelNombreLocal.setText("Nombre del Local:");
        getContentPane().add(jLabelNombreLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 30));

        jLabelEslogan.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelEslogan.setText("Eslogan:");
        getContentPane().add(jLabelEslogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 30));

        jLabelTelefono.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelTelefono.setText("Teléfono:");
        getContentPane().add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, 30));

        jLabelCedulaJuridica.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelCedulaJuridica.setText("Cédula Jurídica");
        getContentPane().add(jLabelCedulaJuridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 150, 30));

        jLabelHorario.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelHorario.setText("Horario de Ateción:");
        getContentPane().add(jLabelHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 150, 30));

        jLabelSiguienteFactura.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelSiguienteFactura.setText("Siguiente Factura:");
        getContentPane().add(jLabelSiguienteFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 40));

        jTextFieldNombreLocal.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        getContentPane().add(jTextFieldNombreLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 420, 40));

        jTextFieldEslogan.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        getContentPane().add(jTextFieldEslogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 420, 40));

        jTextFieldTelefono.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        getContentPane().add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 420, 40));

        jTextFieldCedulaJuridica.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        getContentPane().add(jTextFieldCedulaJuridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 420, 40));

        jTextFieldHorario.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        getContentPane().add(jTextFieldHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 420, 40));

        jButtonGuardar.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonGuardar.setBorderPainted(false);
        jButtonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGuardarMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 110, 40));

        jButtonAtras.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonAtras.setText("Atrás");
        jButtonAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAtras.setBorderPainted(false);
        jButtonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 110, 40));

        jButtonContrasena.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jButtonContrasena.setText("Cambiar Contrasena");
        jButtonContrasena.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonContrasena.setBorderPainted(false);
        jButtonContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonContrasenaMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 180, 40));

        jLabelContrasena.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        jLabelContrasena.setText("Contrasena Encriptada");
        getContentPane().add(jLabelContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 180, 30));

        jLabelContrasenaEncriptada.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        getContentPane().add(jLabelContrasenaEncriptada, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 150, 30));

        jLabelFactura.setFont(new java.awt.Font("Century Schoolbook", 2, 14)); // NOI18N
        getContentPane().add(jLabelFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 130, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtrasMouseClicked
        this.setVisible(false);
        OpcionesAdministrativas ventana = new OpcionesAdministrativas();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonAtrasMouseClicked

    private void jButtonContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContrasenaMouseClicked
        this.setVisible(false);
        CambiarContrasena ventana = new CambiarContrasena();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonContrasenaMouseClicked

    private void jButtonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardarMouseClicked
        String nombre, eslogan, telefono, cedulaJuridica, horario;
        nombre = this.jTextFieldNombreLocal.getText();
        eslogan = this.jTextFieldEslogan.getText();
        telefono = this.jTextFieldTelefono.getText();
        cedulaJuridica = this.jTextFieldCedulaJuridica.getText();
        horario = this.jTextFieldHorario.getText();
        if(nombre.length() > 0 && eslogan.length() > 0 && telefono.length() > 0 && cedulaJuridica.length() > 0 && horario.length() > 0){
            int respuesta = valores.editarValores(nombre, eslogan, telefono, cedulaJuridica, horario);
            if (respuesta > 0){
                JOptionPane.showMessageDialog(null, "Datos guardados exitosamente");
            }
            else{
                JOptionPane.showMessageDialog(null, "Error al guardar los datos");
            }                      
        }
        else{
            JOptionPane.showMessageDialog(null, "No puede dejar espacios en blanco");
        }
    }//GEN-LAST:event_jButtonGuardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValoresIniciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValoresIniciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValoresIniciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValoresIniciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValoresIniciales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonContrasena;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabelCedulaJuridica;
    private javax.swing.JLabel jLabelContrasena;
    private javax.swing.JLabel jLabelContrasenaEncriptada;
    private javax.swing.JLabel jLabelEslogan;
    private javax.swing.JLabel jLabelFactura;
    private javax.swing.JLabel jLabelHorario;
    private javax.swing.JLabel jLabelNombreLocal;
    private javax.swing.JLabel jLabelSiguienteFactura;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JTextField jTextFieldCedulaJuridica;
    private javax.swing.JTextField jTextFieldEslogan;
    private javax.swing.JTextField jTextFieldHorario;
    private javax.swing.JTextField jTextFieldNombreLocal;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
