/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.util.ArrayList;
import manejoDeDatos.ValoresIniciales;

/**
 *
 * @author Jordan Araya
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    ValoresIniciales valores = new ValoresIniciales();
    ArrayList<String> datos = new ArrayList<>();
    
    
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        datosInciales();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    public void datosInciales(){
        datos = valores.getDatos();
        inicioNombre.setText(datos.get(0));
        inicioCedula.setText(datos.get(1));
        inicioEslogan.setText(datos.get(2));
        inicioHorario.setText(datos.get(4));
        inicioTelefono.setText(datos.get(3));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        inicioTelefono = new javax.swing.JLabel();
        inicioHorario = new javax.swing.JLabel();
        inicioEslogan = new javax.swing.JLabel();
        inicioCedula = new javax.swing.JLabel();
        inicioNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jButton1.setText("Área Administrativa");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 280, 60));

        jButton2.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jButton2.setText("Opciones Generales");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 280, 60));

        jButton3.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jButton3.setText("Salir");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 370, 280, 60));

        inicioTelefono.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        inicioTelefono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(inicioTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 320, 30));

        inicioHorario.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        inicioHorario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(inicioHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 320, 30));

        inicioEslogan.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        inicioEslogan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(inicioEslogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 320, 30));

        inicioCedula.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        inicioCedula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(inicioCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 320, 30));

        inicioNombre.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        inicioNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(inicioNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 320, 30));

        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 530, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login ingreso = new Login();
        ingreso.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        OpcionesGenerales generales = new OpcionesGenerales();
        generales.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PantallaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel inicioCedula;
    private javax.swing.JLabel inicioEslogan;
    private javax.swing.JLabel inicioHorario;
    private javax.swing.JLabel inicioNombre;
    private javax.swing.JLabel inicioTelefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
