/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import BD.ManejoComponentes;
import BD.ManejoDatos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jordan Araya
 */
public class ClienteVehiculo extends javax.swing.JFrame {
    ManejoDatos Conectar = new ManejoDatos();
    ManejoComponentes Componentes = new ManejoComponentes();
    /**
     * Creates new form ClienteVehiculo
     */
    public ClienteVehiculo() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        Componentes.llenarTablas(jTableClientes,jTableClientes.getColumnCount(),"SELECT * FROM InformacionCliente");
        Componentes.llenarTablas(jTableVehiculos, jTableVehiculos.getColumnCount(),""
                       + "SELECT V.MatriculaVehiculo,MarcaVehiculo,V.ModeloVehiculo,V.ColorVehiculo,V.FechaEntrada,I.Dueño "
                       + " FROM vehiculo V inner join InformacionCliente  I on I.CedulaCliente = V.CedulaCliente");
    }
    private void vaciarCL(){
        jTextFieldNombreCL.setText("");
        jTextFieldApellido1CL.setText("");
        jTextFieldApellido2CL.setText("");
        jTextFieldCedulaCL.setText("");
        jTextAreaDireccionCL.setText("");
        jTextFieldTelefonoCL.setText("");
    }
    private void vaciasVH(){
        jTextFieldMatriculaVH.setText("");
        jTextFieldColorVH.setText("");
        jTextFieldNombreVH.setText("");
        jComboBoxClienteVH.setSelectedItem("");
        jTextFieldModeloVH.setText("");
        jTextFieldMarcaVH.setText("");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuCL = new javax.swing.JPopupMenu();
        jMenuItemEliminarCL = new javax.swing.JMenuItem();
        jPopupMenuVH = new javax.swing.JPopupMenu();
        jMenuItemEliminarVH = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldApellido2CL = new javax.swing.JTextField();
        jTextFieldApellido1CL = new javax.swing.JTextField();
        jTextFieldCedulaCL = new javax.swing.JTextField();
        jTextFieldNombreCL = new javax.swing.JTextField();
        jTextFieldTelefonoCL = new javax.swing.JTextField();
        jButtonAgregarCL = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDireccionCL = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldMatriculaVH = new javax.swing.JTextField();
        jTextFieldModeloVH = new javax.swing.JTextField();
        jComboBoxClienteVH = new javax.swing.JComboBox<>();
        jTextFieldNombreVH = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButtonAgregarVehiculo = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldColorVH = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldMarcaVH = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableVehiculos = new javax.swing.JTable();
        jButtonVolver = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        jMenuItemEliminarCL.setText("Eliminar Cliente");
        jMenuItemEliminarCL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarCLActionPerformed(evt);
            }
        });
        jPopupMenuCL.add(jMenuItemEliminarCL);

        jMenuItemEliminarVH.setText("Eliminar Vehiculo");
        jMenuItemEliminarVH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarVHActionPerformed(evt);
            }
        });
        jPopupMenuVH.add(jMenuItemEliminarVH);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Area Clientes - Vehiculos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Nuevo Cliente", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre Cliente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jLabel3.setText("Cedula Cliente:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        jLabel4.setText("Apellido 1 Cliente:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        jLabel5.setText("Apellido 2 Cliente:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        jLabel6.setText("Telefono Cliente:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        jLabel7.setText("Direccion:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        jPanel1.add(jTextFieldApellido2CL, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 180, -1));
        jPanel1.add(jTextFieldApellido1CL, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 180, -1));
        jPanel1.add(jTextFieldCedulaCL, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 180, -1));
        jPanel1.add(jTextFieldNombreCL, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 180, -1));

        jTextFieldTelefonoCL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoCLActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTelefonoCL, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 180, -1));

        jButtonAgregarCL.setText("Agregar Cliente");
        jButtonAgregarCL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarCLActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAgregarCL, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 170, -1));

        jTextAreaDireccionCL.setColumns(20);
        jTextAreaDireccionCL.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDireccionCL);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 370, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 300));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes Registrados"));

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Completo", "Cedula", "Telefono", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClientes.setComponentPopupMenu(jPopupMenuCL);
        jTableClientes.setGridColor(new java.awt.Color(153, 153, 153));
        jTableClientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableClientes);
        if (jTableClientes.getColumnModel().getColumnCount() > 0) {
            jTableClientes.getColumnModel().getColumn(0).setResizable(false);
            jTableClientes.getColumnModel().getColumn(0).setPreferredWidth(120);
            jTableClientes.getColumnModel().getColumn(1).setResizable(false);
            jTableClientes.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTableClientes.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTableClientes.getColumnModel().getColumn(3).setPreferredWidth(250);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 820, 300));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Un Vehiculo"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Matricula (Placa) :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        jLabel10.setText("Dueño (Cliente): ");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        jLabel11.setText("Nombre:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));
        jPanel3.add(jTextFieldMatriculaVH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 120, -1));
        jPanel3.add(jTextFieldModeloVH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 120, -1));

        jComboBoxClienteVH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxClienteVHMouseClicked(evt);
            }
        });
        jComboBoxClienteVH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClienteVHActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxClienteVH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 120, -1));

        jTextFieldNombreVH.setEnabled(false);
        jPanel3.add(jTextFieldNombreVH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 220, -1));

        jLabel13.setText("Color:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        jButtonAgregarVehiculo.setText("Ingresar Vehiculo");
        jButtonAgregarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarVehiculoActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAgregarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 170, -1));

        jLabel14.setText("Marca:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));
        jPanel3.add(jTextFieldColorVH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 120, -1));

        jLabel16.setText("Modelo:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));
        jPanel3.add(jTextFieldMarcaVH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 120, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 510, 280));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehiculos Ingresados"));

        jTableVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Marca", "Modelo", "Color", "Fecha/ Hora de  Entrada", "Dueño"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVehiculos.setComponentPopupMenu(jPopupMenuVH);
        jTableVehiculos.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableVehiculos);
        if (jTableVehiculos.getColumnModel().getColumnCount() > 0) {
            jTableVehiculos.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTableVehiculos.getColumnModel().getColumn(5).setPreferredWidth(200);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 820, 310));

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 690, 120, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Ayuda"));

        jLabel15.setText("Para  Eliminar, selecionar un registro de la tabla y presionar click derecho.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 690, 510, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTelefonoCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoCLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoCLActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        PaginaPrincipal Volver = new PaginaPrincipal();
        Volver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonAgregarCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarCLActionPerformed
        if(jTextFieldNombreCL.getText().isEmpty() | jTextFieldApellido1CL.getText().isEmpty()|
                jTextFieldApellido2CL.getText().isEmpty() | jTextFieldCedulaCL.getText().isEmpty()
                | jTextAreaDireccionCL.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Todos los campos deben ser llenados","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else{  
            try {
                String ced = jTextFieldCedulaCL.getText();
                String nom = jTextFieldNombreCL.getText();
                String ape1 = jTextFieldApellido1CL.getText();
                String ape2 = jTextFieldApellido2CL.getText();
                String dir = jTextAreaDireccionCL.getText();
                String tel = jTextFieldTelefonoCL.getText();
                String sql = "CALL AgregarCliente('"+ced+"','"+nom+"','"+ape1+"','"+ape2+"','"+dir+"','"+tel+"')";
                Conectar.ExecutarConsulta(sql);
                Componentes.limpiarTabla(jTableClientes);
                Componentes.llenarTablas(jTableClientes,jTableClientes.getColumnCount(),"SELECT * FROM InformacionCliente");
                vaciarCL();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ClienteVehiculo.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this,"Error 1 "+ex,"Aviso",JOptionPane.INFORMATION_MESSAGE);

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"La cedula ingresada ya existe para otro cliente, Verificar Datos","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_jButtonAgregarCLActionPerformed

    private void jButtonAgregarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarVehiculoActionPerformed
       if(jTextFieldMatriculaVH.getText().isEmpty() | jTextFieldModeloVH.getText().isEmpty() |
               jTextFieldColorVH.getText().isEmpty() | jComboBoxClienteVH.getSelectedItem().toString().isEmpty()){
           JOptionPane.showMessageDialog(this, "Todos los espacios deben ser llenados","ERROR",JOptionPane.ERROR_MESSAGE);
       }
       else{
           try {
               String placa = jTextFieldMatriculaVH.getText();
               String marca = jTextFieldMarcaVH.getText();
               String modelo = jTextFieldModeloVH.getText();
               String color = jTextFieldColorVH.getText();
               String ced = jComboBoxClienteVH.getSelectedItem().toString();
               String sql = "CALL AgregarVehiculo('"+placa+"','"+marca+"','"+modelo+"','"+color+"','"+ced+"')";
               Conectar.ExecutarConsulta(sql);
               Componentes.limpiarTabla(jTableVehiculos);
               Componentes.llenarTablas(jTableVehiculos, jTableVehiculos.getColumnCount(),""
                       + "SELECT V.MatriculaVehiculo,MarcaVehiculo,V.ModeloVehiculo,V.ColorVehiculo,V.FechaEntrada,I.Dueño "
                       + " FROM vehiculo V inner join InformacionCliente  I on I.CedulaCliente = V.CedulaCliente");
               vaciasVH();
           } catch (ClassNotFoundException ex) {
               JOptionPane.showMessageDialog(this, "Hubo un error inesperado "+ex,"ERROR",JOptionPane.ERROR_MESSAGE);
               Logger.getLogger(ClienteVehiculo.class.getName()).log(Level.SEVERE, null, ex);
           } catch (SQLException ex) {
               JOptionPane.showMessageDialog(this,"La placa ya esta registrada para otro vehiculo, Verificar Datos ","ERROR",JOptionPane.ERROR_MESSAGE);
               Logger.getLogger(ClienteVehiculo.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    }//GEN-LAST:event_jButtonAgregarVehiculoActionPerformed

    private void jMenuItemEliminarCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarCLActionPerformed
        System.out.println(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),1).toString());
        try {
            String sql  = "DELETE FROM clientes WHERE CedulaCliente = '"+jTableClientes.getValueAt(jTableClientes.getSelectedRow(),1).toString()+"'";
            Conectar.ExecutarConsulta(sql);
            Componentes.limpiarTabla(jTableClientes);
            Componentes.llenarTablas(jTableClientes,jTableClientes.getColumnCount(),"SELECT * FROM InformacionCliente");

        } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"El cliente tiene un Vehiculo asociado, No se puede Eliminar","ERROR",JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(ClienteVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"Hubo un error inesperado "+ex);
            //Logger.getLogger(ClienteVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemEliminarCLActionPerformed

    private void jComboBoxClienteVHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxClienteVHMouseClicked
        try {
            jComboBoxClienteVH.removeAllItems();
            Componentes.llenarCombobox(jComboBoxClienteVH,"SELECT CedulaCliente FROM clientes","CedulaCliente");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClienteVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ClienteVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBoxClienteVHMouseClicked

    private void jComboBoxClienteVHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClienteVHActionPerformed
        if(jComboBoxClienteVH.getSelectedIndex()==-1){
            jTextFieldNombreVH.setText("");
        }
        else{
            try {
                 String dueño = Conectar.duenhoVehiculo(jComboBoxClienteVH.getSelectedItem().toString());
                 jTextFieldNombreVH.setText(dueño);      
            } catch (SQLException ex) {
                Logger.getLogger(ClienteVehiculo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ClienteVehiculo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jComboBoxClienteVHActionPerformed

    private void jMenuItemEliminarVHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarVHActionPerformed
        try {
            String sql = "DELETE FROM vehiculo WHERE MatriculaVehiculo ='"+jTableVehiculos.getValueAt(jTableVehiculos.getSelectedRow(),0).toString()+"'";
            System.out.println(sql);
            Conectar.ExecutarConsulta(sql);
            Componentes.limpiarTabla(jTableVehiculos);
            Componentes.llenarTablas(jTableVehiculos, jTableVehiculos.getColumnCount(),""
                       + "SELECT V.MatriculaVehiculo,MarcaVehiculo,V.ModeloVehiculo,V.ColorVehiculo,V.FechaEntrada,I.Dueño "
                       + " FROM vehiculo V inner join InformacionCliente  I on I.CedulaCliente = V.CedulaCliente");
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this,"El vehiculo Seleccionado esta en reparacion, No puede ser eliminado","ERROR",JOptionPane.ERROR_MESSAGE);
//Logger.getLogger(ClienteVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClienteVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemEliminarVHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarCL;
    private javax.swing.JButton jButtonAgregarVehiculo;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxClienteVH;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItemEliminarCL;
    private javax.swing.JMenuItem jMenuItemEliminarVH;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenuCL;
    private javax.swing.JPopupMenu jPopupMenuVH;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTable jTableVehiculos;
    private javax.swing.JTextArea jTextAreaDireccionCL;
    private javax.swing.JTextField jTextFieldApellido1CL;
    private javax.swing.JTextField jTextFieldApellido2CL;
    private javax.swing.JTextField jTextFieldCedulaCL;
    private javax.swing.JTextField jTextFieldColorVH;
    private javax.swing.JTextField jTextFieldMarcaVH;
    private javax.swing.JTextField jTextFieldMatriculaVH;
    private javax.swing.JTextField jTextFieldModeloVH;
    private javax.swing.JTextField jTextFieldNombreCL;
    private javax.swing.JTextField jTextFieldNombreVH;
    private javax.swing.JTextField jTextFieldTelefonoCL;
    // End of variables declaration//GEN-END:variables
}
