/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import BD.*;
import Facturacion.CrearFactura;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import org.jdom2.JDOMException;

/**
 *
 * @author Jordan Araya
 */
public class FacturasReportes extends javax.swing.JFrame {
    ManejoComponentes componentes  = new ManejoComponentes();
    ManejoDatos conectar = new ManejoDatos();
    CrearFactura facturar = new  CrearFactura();
    String moneda ="";
    
    /**
     * Creates new form FacturasReportes
     */
    public FacturasReportes() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        componentes.llenarTablas(jTablefacturas,jTablefacturas.getColumnCount(),
        "SELECT FcNumero, FcFecha, FcIDReparacion, FcCedulaCliente, IfNombreCompleto," +
        " FcMoneda, FcTC,SubTotalColones, ImpuestoCRC,DescuendoCRC,TotalColones ,"+
        " SubTotalDolares,ImpuestoUSD,DescuentoUSD,TotalDolares FROM Facturacion "
                + "GROUP BY FcNumero"); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMoneda = new javax.swing.ButtonGroup();
        jPopupMenuVerFC = new javax.swing.JPopupMenu();
        jMenuItemFacturas = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtonCRC = new javax.swing.JRadioButton();
        jRadioButtonUSD = new javax.swing.JRadioButton();
        jComboBoxReparaciones = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTipoCambio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDescuento = new javax.swing.JTextField();
        jButtonGenerarFactura = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablefacturas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        jMenuItemFacturas.setText("Ver Factura");
        jMenuItemFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFacturasActionPerformed(evt);
            }
        });
        jPopupMenuVerFC.add(jMenuItemFacturas);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Generar Factura por Reparaciones"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Repracion a Facturar : ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Moneda"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroupMoneda.add(jRadioButtonCRC);
        jRadioButtonCRC.setText("CRC");
        jRadioButtonCRC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonCRCMouseClicked(evt);
            }
        });
        jPanel2.add(jRadioButtonCRC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        buttonGroupMoneda.add(jRadioButtonUSD);
        jRadioButtonUSD.setText("USD");
        jRadioButtonUSD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonUSDMouseClicked(evt);
            }
        });
        jPanel2.add(jRadioButtonUSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 50));

        jComboBoxReparaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxReparacionesMouseClicked(evt);
            }
        });
        jPanel1.add(jComboBoxReparaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 60, -1));

        jLabel2.setText("Tipo de Cambio a Facturar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));
        jPanel1.add(jTextFieldTipoCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 60, -1));

        jLabel3.setText("Descuento (%) :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        jPanel1.add(jTextFieldDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 60, -1));

        jButtonGenerarFactura.setText("Generar Factura");
        jButtonGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGenerarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 340, 190));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Facturas Generadas"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablefacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. FC", "Fecha/Hora FC", "ID Reparacion", "Cedula Cliente", "Nombre Cliente", "Moneda", "TC", "Sub Total CRC", "Impuesto CRC", "Descuento CRC", "Total CRC", "Sub Total USD", "Impuesto USD", "Descuento USD", "Total USD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablefacturas.setComponentPopupMenu(jPopupMenuVerFC);
        jTablefacturas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTablefacturas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTablefacturas);
        if (jTablefacturas.getColumnModel().getColumnCount() > 0) {
            jTablefacturas.getColumnModel().getColumn(0).setResizable(false);
            jTablefacturas.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTablefacturas.getColumnModel().getColumn(1).setResizable(false);
            jTablefacturas.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTablefacturas.getColumnModel().getColumn(2).setResizable(false);
            jTablefacturas.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTablefacturas.getColumnModel().getColumn(3).setResizable(false);
            jTablefacturas.getColumnModel().getColumn(3).setPreferredWidth(75);
            jTablefacturas.getColumnModel().getColumn(4).setResizable(false);
            jTablefacturas.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTablefacturas.getColumnModel().getColumn(5).setResizable(false);
            jTablefacturas.getColumnModel().getColumn(5).setPreferredWidth(50);
            jTablefacturas.getColumnModel().getColumn(6).setResizable(false);
            jTablefacturas.getColumnModel().getColumn(6).setPreferredWidth(50);
            jTablefacturas.getColumnModel().getColumn(7).setResizable(false);
            jTablefacturas.getColumnModel().getColumn(7).setPreferredWidth(100);
            jTablefacturas.getColumnModel().getColumn(8).setResizable(false);
            jTablefacturas.getColumnModel().getColumn(8).setPreferredWidth(80);
            jTablefacturas.getColumnModel().getColumn(9).setResizable(false);
            jTablefacturas.getColumnModel().getColumn(9).setPreferredWidth(75);
            jTablefacturas.getColumnModel().getColumn(10).setResizable(false);
            jTablefacturas.getColumnModel().getColumn(10).setPreferredWidth(100);
            jTablefacturas.getColumnModel().getColumn(11).setResizable(false);
            jTablefacturas.getColumnModel().getColumn(11).setPreferredWidth(150);
            jTablefacturas.getColumnModel().getColumn(14).setResizable(false);
            jTablefacturas.getColumnModel().getColumn(14).setPreferredWidth(100);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 1480, 580));

        jScrollPane2.setViewportView(jPanel3);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 970, 620));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Area de reportes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Reporte de Todos los Vehiculos Reparados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 270, -1));

        jButton3.setText("Reporte de Todos Los datos de las Reparaciones");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 270, -1));

        jButton4.setText("Reporte de Todos los repuestos Utilizados");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 270, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 320, 140));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 700, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Ayuda"));

        jLabel14.setText("Para  Ver Factura, selecionar un registro de la tabla y presionar click derecho.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 690, 510, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarFacturaActionPerformed
        if(jComboBoxReparaciones.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this,"NO selecciono una reparacion","AVISO",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(jTextFieldDescuento.getText().isEmpty()|jTextFieldTipoCambio.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Los campos de DESCUENTO y TIPO CAMBIO, NO pueden ser vacios");
        }
        else if (moneda.isEmpty()){
            JOptionPane.showMessageDialog(this,"NO selecciono una Moneda");
        }
        else{
            try {
                String IDrep = jComboBoxReparaciones.getSelectedItem().toString();
                double TC = Double.valueOf(jTextFieldTipoCambio.getText());
                double Desc = Double.valueOf(jTextFieldDescuento.getText());
                String sql ="call AgregarFactura ("+IDrep+",'"+moneda+"',"+TC+","+Desc+")";
                conectar.ExecutarConsulta(sql);
                String numero = conectar.NumeroFactura(jComboBoxReparaciones.getSelectedItem().toString());
                String Nombre = facturar.CrearFactura(Integer.valueOf(numero));
                 int reply = JOptionPane.showConfirmDialog(null, "¿Desea Visualizar la Factura?","Visualizacion", JOptionPane.YES_NO_OPTION);
                 if(reply==JOptionPane.YES_OPTION){    
                     facturar.visualizarFactura(Nombre);
                 }
            componentes.limpiarTabla(jTablefacturas);
            componentes.llenarTablas(jTablefacturas,jTablefacturas.getColumnCount(),
              "SELECT FcNumero, FcFecha, FcIDReparacion, FcCedulaCliente, IfNombreCompleto," +
            " FcMoneda, FcTC,SubTotalColones, ImpuestoCRC,DescuendoCRC,TotalColones ,"+
            " SubTotalDolares,ImpuestoUSD,DescuentoUSD,TotalDolares FROM Facturacion "
                + "GROUP BY FcNumero");
            String modificar = "UPDATE reparacion SET EstadoReparacion = 0 WHERE idReparacion = "+jComboBoxReparaciones.getSelectedItem().toString();
            conectar.ExecutarConsulta(modificar);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FacturasReportes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(FacturasReportes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (JRException ex) {
                Logger.getLogger(FacturasReportes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (JDOMException ex) {
                Logger.getLogger(FacturasReportes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(FacturasReportes.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(this,"Los campos Tipo Cambio y Descuento deben ser numeros","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonGenerarFacturaActionPerformed

    private void jRadioButtonCRCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonCRCMouseClicked
        moneda="CRC";
    }//GEN-LAST:event_jRadioButtonCRCMouseClicked

    private void jRadioButtonUSDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonUSDMouseClicked
       moneda="USD";
    }//GEN-LAST:event_jRadioButtonUSDMouseClicked

    private void jComboBoxReparacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxReparacionesMouseClicked
            try {
                jComboBoxReparaciones.removeAllItems();
                componentes.llenarCombobox(jComboBoxReparaciones,"SELECT idReparacion FROM reparacion WHERE EstadoReparacion=1", "idReparacion");
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex);
                Logger.getLogger(FacturasReportes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
                Logger.getLogger(FacturasReportes.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }//GEN-LAST:event_jComboBoxReparacionesMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       PaginaPrincipal volver = new PaginaPrincipal();
       volver.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFacturasActionPerformed
        if(jTablefacturas.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this,"NO selecciono nada ","AVISO",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            String  fact = "Factura Numero "+jTablefacturas.getValueAt(jTablefacturas.getSelectedRow(),0)+".pdf";
            try {
                facturar.visualizarFactura(fact);
            } catch (JDOMException ex) {
                Logger.getLogger(FacturasReportes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(FacturasReportes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItemFacturasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       VehiculosReparadosReport infoVH = new VehiculosReparadosReport();
       infoVH.setVisible(true);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       RepuestosUtilizados repuestos = new RepuestosUtilizados();
       repuestos.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TodosDatosReparacion TodoRep = new TodosDatosReparacion();
        TodoRep.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturasReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturasReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturasReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturasReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FacturasReportes().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupMoneda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonGenerarFactura;
    private javax.swing.JComboBox<String> jComboBoxReparaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItemFacturas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenuVerFC;
    private javax.swing.JRadioButton jRadioButtonCRC;
    private javax.swing.JRadioButton jRadioButtonUSD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablefacturas;
    private javax.swing.JTextField jTextFieldDescuento;
    private javax.swing.JTextField jTextFieldTipoCambio;
    // End of variables declaration//GEN-END:variables
}
