/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import BD.ManejoComponentes;
import BD.ManejoDatos;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jordan Araya
 */
public class Mecanicos extends javax.swing.JFrame {
    ManejoComponentes componente = new ManejoComponentes();
    ManejoDatos conectar = new ManejoDatos();

    /**
     * Creates new form Mecanicos
     * 
     */
    public Mecanicos() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        componente.llenarTablas(jTableMecanicos,jTableMecanicos.getColumnCount(),""
                    + "SELECT CedulaMecanico, NombreMecanico FROM mecanicos");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuMC = new javax.swing.JPopupMenu();
        jMenuItemEliminarMC = new javax.swing.JMenuItem();
        jPopupMenuListadp = new javax.swing.JPopupMenu();
        jMenuItemEliminarLinea = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jButtonAgregarMC = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCedulaMC = new javax.swing.JTextField();
        jTextFieldNombreMC = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMecanicos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxRepuesto = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNombreRE = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldManoObra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxReparacion = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListadoRepuestos = new javax.swing.JTable();
        jButtonAgregarLinea = new javax.swing.JButton();
        jButtonAregarListado = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldPlacaVHRE = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldCienteVHRE = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jComboBoxMecanicos = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNombreMCR = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxReparaciones = new javax.swing.JComboBox<>();
        jButtonAgregarMCRP = new javax.swing.JButton();
        jTextFieldCienteVH = new javax.swing.JTextField();
        jTextFieldPlacaVH = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButtonMecEnRep = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        jMenuItemEliminarMC.setText("Eliminar Mecanico");
        jMenuItemEliminarMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarMCActionPerformed(evt);
            }
        });
        jPopupMenuMC.add(jMenuItemEliminarMC);

        jMenuItemEliminarLinea.setText("Eliminar Linea");
        jMenuItemEliminarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarLineaActionPerformed(evt);
            }
        });
        jPopupMenuListadp.add(jMenuItemEliminarLinea);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Area Mecanicos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Nuevo Mecanico"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAgregarMC.setText("Agregar Mecanico");
        jButtonAgregarMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarMCActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAgregarMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 130, -1));

        jLabel2.setText("Cedula Mecanico:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        jLabel3.setText("Nombre Mecanico:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));
        jPanel1.add(jTextFieldCedulaMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 110, -1));

        jTextFieldNombreMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreMCActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNombreMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 260, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 404, 160));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Mecanicos Agregados"));

        jTableMecanicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula ", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Byte.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMecanicos.setComponentPopupMenu(jPopupMenuMC);
        jTableMecanicos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableMecanicos);
        if (jTableMecanicos.getColumnModel().getColumnCount() > 0) {
            jTableMecanicos.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableMecanicos.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 730, 250));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Repuestos a una Reparacion"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Repuesto");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        jComboBoxRepuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxRepuestoMouseClicked(evt);
            }
        });
        jComboBoxRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRepuestoActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 70, -1));

        jLabel6.setText("Nombre:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, 20));

        jTextFieldNombreRE.setEnabled(false);
        jTextFieldNombreRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreREActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldNombreRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        jLabel7.setText("Mano Obra:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, -1, 20));
        jPanel3.add(jTextFieldManoObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 80, -1));

        jLabel8.setText("Numero de Reparacion a incluir los Repuestos: ");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        jComboBoxReparacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxReparacionMouseClicked(evt);
            }
        });
        jComboBoxReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxReparacionActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxReparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 60, 20));

        jTableListadoRepuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Repuesto", "Nombre Repuesto", "Precio Unitario", "Cantidad", "Monto Mano Obra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListadoRepuestos.setComponentPopupMenu(jPopupMenuListadp);
        jTableListadoRepuestos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableListadoRepuestos);
        if (jTableListadoRepuestos.getColumnModel().getColumnCount() > 0) {
            jTableListadoRepuestos.getColumnModel().getColumn(0).setResizable(false);
            jTableListadoRepuestos.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableListadoRepuestos.getColumnModel().getColumn(1).setResizable(false);
            jTableListadoRepuestos.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTableListadoRepuestos.getColumnModel().getColumn(2).setResizable(false);
            jTableListadoRepuestos.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTableListadoRepuestos.getColumnModel().getColumn(3).setResizable(false);
            jTableListadoRepuestos.getColumnModel().getColumn(3).setPreferredWidth(5);
            jTableListadoRepuestos.getColumnModel().getColumn(4).setResizable(false);
            jTableListadoRepuestos.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 830, 240));

        jButtonAgregarLinea.setText("Agregar");
        jButtonAgregarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarLineaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAgregarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 100, -1));

        jButtonAregarListado.setText("Agregar Listado a Reparacion");
        jButtonAregarListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAregarListadoActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAregarListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 220, -1));

        jLabel15.setText("Precio:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, 20));
        jPanel3.add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 50, -1));

        jLabel16.setText("Cantidad:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, 20));

        jTextFieldPrecio.setEnabled(false);
        jPanel3.add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 60, -1));

        jLabel13.setText("Placa vehiculo:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, 20));

        jTextFieldPlacaVHRE.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldPlacaVHRE.setEnabled(false);
        jPanel3.add(jTextFieldPlacaVHRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 90, 20));

        jLabel12.setText("Nombre Cliente:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jTextFieldCienteVHRE.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldCienteVHRE.setEnabled(false);
        jPanel3.add(jTextFieldCienteVHRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 260, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 920, 400));

        jButton4.setText("Volver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1213, 700, 90, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Mecanico a una Reparacion"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxMecanicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxMecanicosMouseClicked(evt);
            }
        });
        jComboBoxMecanicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMecanicosActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBoxMecanicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 53, 120, -1));

        jLabel9.setText("Mecanico: ");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 56, -1, -1));

        jLabel10.setText("Nombre Mecanico: ");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 94, -1, -1));

        jTextFieldNombreMCR.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldNombreMCR.setEnabled(false);
        jPanel4.add(jTextFieldNombreMCR, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 260, -1));

        jLabel11.setText("Reparaciones:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jComboBoxReparaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxReparacionesMouseClicked(evt);
            }
        });
        jComboBoxReparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxReparacionesActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBoxReparaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 120, -1));

        jButtonAgregarMCRP.setText("Agregar");
        jButtonAgregarMCRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarMCRPActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonAgregarMCRP, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 110, -1));

        jTextFieldCienteVH.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldCienteVH.setEnabled(false);
        jPanel4.add(jTextFieldCienteVH, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 260, -1));

        jTextFieldPlacaVH.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldPlacaVH.setEnabled(false);
        jPanel4.add(jTextFieldPlacaVH, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 120, -1));

        jLabel17.setText("Placa vehiculo:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel18.setText("Nombre Cliente:");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jButtonMecEnRep.setText("Ver Mecanicos Por Reparación ");
        jButtonMecEnRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMecEnRepActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonMecEnRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 410, 300));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Ayuda"));

        jLabel14.setText("Para  Eliminar, selecionar un registro de la tabla y presionar click derecho.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 690, 510, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreMCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreMCActionPerformed

    private void jTextFieldNombreREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreREActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        PaginaPrincipal Volver = new PaginaPrincipal();
        Volver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonAgregarMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarMCActionPerformed
        try {
            String CedMc = jTextFieldCedulaMC.getText();
            String NomMc = jTextFieldNombreMC.getText();       
            String sql = " CALL AgregarMecanico('"+CedMc+"','"+NomMc+"')";
            conectar.ExecutarConsulta(sql);
            componente.limpiarTabla(jTableMecanicos);
            componente.llenarTablas(jTableMecanicos,jTableMecanicos.getColumnCount(),""
                    + "SELECT CedulaMecanico, NombreMecanico FROM mecanicos");
            jTextFieldCedulaMC.setText("");
            jTextFieldNombreMC.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonAgregarMCActionPerformed

    private void jMenuItemEliminarMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarMCActionPerformed
        try {
            String sql = "DELETE FROM mecanicos WHERE CedulaMecanico ="+Integer.valueOf(jTableMecanicos.getValueAt(jTableMecanicos.getSelectedRow(),0).toString());
            System.out.println(sql);
            conectar.ExecutarConsulta(sql);
            componente.limpiarTabla(jTableMecanicos);
            componente.llenarTablas(jTableMecanicos,jTableMecanicos.getColumnCount(),""
                    + "SELECT CedulaMecanico, NombreMecanico FROM mecanicos");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "El mecánico esta asociado a una reparacion, No se Puede Eliminar","ERROR",JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemEliminarMCActionPerformed

    private void jComboBoxMecanicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxMecanicosMouseClicked
        try {
            jComboBoxMecanicos.removeAllItems();
            componente.llenarCombobox(jComboBoxMecanicos,"SELECT CedulaMecanico FROM mecanicos", "CedulaMecanico");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBoxMecanicosMouseClicked

    private void jComboBoxMecanicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMecanicosActionPerformed
        if(jComboBoxMecanicos.getSelectedIndex()==-1){
            jTextFieldNombreMCR.setText("");
        }
        else{
            try {
               String nombre= conectar.nonbreMecanico(jComboBoxMecanicos.getSelectedItem().toString());
               jTextFieldNombreMCR.setText(nombre);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jComboBoxMecanicosActionPerformed

    private void jComboBoxReparacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxReparacionesMouseClicked
            try {
                jComboBoxReparaciones.removeAllItems();
                componente.llenarCombobox(jComboBoxReparaciones,"SELECT idReparacion FROM reparacion WHERE EstadoReparacion=1 ","idReparacion");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBoxReparacionesMouseClicked

    private void jComboBoxReparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxReparacionesActionPerformed
        if(jComboBoxReparaciones.getSelectedIndex()==-1){
            jTextFieldCienteVH.setText("");
            jTextFieldCienteVH.setText("");
        }
        else{
            try {
                ArrayList datos = conectar.nombrePlaca(Integer.valueOf(jComboBoxReparaciones.getSelectedItem().toString()));
                jTextFieldPlacaVH.setText(datos.get(0).toString());
                jTextFieldCienteVH.setText(datos.get(1).toString());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jComboBoxReparacionesActionPerformed

    private void jButtonAgregarMCRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarMCRPActionPerformed
        if(jComboBoxReparaciones.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this,"Se debe seleccionar una reparacion de la lista","AVISO",JOptionPane.INFORMATION_MESSAGE);
        }
        else if (jComboBoxMecanicos.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this, "Se debe seleccionar un mecanico de la lista","AVISO",JOptionPane.INFORMATION_MESSAGE);
        }else{
            try {
                String IDMec = jComboBoxMecanicos.getSelectedItem().toString();
                String IDRep = jComboBoxReparaciones.getSelectedItem().toString();
                String sql = "CALL MecanicosEnReparaciones ("+IDMec+","+IDRep+")";
                conectar.ExecutarConsulta(sql);
                JOptionPane.showMessageDialog(this,"Se Agrego a "+jTextFieldNombreMCR.getText() + " A la reparacion  del "
                        + "Vechiculo Placa: "+jTextFieldPlacaVH.getText());
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this,"Hubo un error inesperado "+ex,"ERROR",JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"No se pueden agregar mecanicos a una misma reparacion","ERROR",JOptionPane.ERROR_MESSAGE);
                System.out.println(ex);
            }
            
        }          
    }//GEN-LAST:event_jButtonAgregarMCRPActionPerformed

    private void jComboBoxReparacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxReparacionMouseClicked
        try {
            jComboBoxReparacion.removeAllItems();
            componente.llenarCombobox(jComboBoxReparacion,"SELECT idReparacion FROM reparacion WHERE EstadoReparacion = 1","Idreparacion");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jComboBoxReparacionMouseClicked

    private void jComboBoxRepuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxRepuestoMouseClicked
        try {
            jComboBoxRepuesto.removeAllItems();
            componente.llenarCombobox(jComboBoxRepuesto,"SELECT IdRepuesto FROM repuestos", "IdRepuesto");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jComboBoxRepuestoMouseClicked

    private void jComboBoxRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRepuestoActionPerformed
        if(jComboBoxRepuesto.getSelectedIndex()==-1){
            jTextFieldNombreRE.setText("");
            jTextFieldPrecio.setText("");
        }
        else{
            try {
                ArrayList datos = conectar.nombreprecioRE(Integer.valueOf(jComboBoxRepuesto.getSelectedItem().toString()));
                jTextFieldNombreRE.setText(datos.get(0).toString());
                jTextFieldPrecio.setText(datos.get(1).toString());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jComboBoxRepuestoActionPerformed

    private void jComboBoxReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxReparacionActionPerformed
       if(jComboBoxReparacion.getSelectedIndex()==-1){
            jTextFieldCienteVHRE.setText("");
            jTextFieldCienteVHRE.setText("");
        }
       else{
            try {
                ArrayList datos = conectar.nombrePlaca(Integer.valueOf(jComboBoxReparacion.getSelectedItem().toString()));
                jTextFieldPlacaVHRE.setText(datos.get(0).toString());
                jTextFieldCienteVHRE.setText(datos.get(1).toString());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
    }//GEN-LAST:event_jComboBoxReparacionActionPerformed

    private void jButtonAgregarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarLineaActionPerformed
        if(jComboBoxRepuesto.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this,"Se debe elegir un repuesto","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if(jTextFieldPrecio.getText().isEmpty() | jTextFieldManoObra.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Campo precio y cantidad deben ser llenados","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                ArrayList datos = new ArrayList();
                datos.add(jComboBoxRepuesto.getSelectedItem().toString());
                datos.add(jTextFieldNombreRE.getText());
                datos.add(jTextFieldPrecio.getText());
                datos.add(jTextFieldCantidad.getText());
                datos.add(jTextFieldManoObra.getText());
                componente.llenarTablaRE(jTableListadoRepuestos, datos);
                jTextFieldCantidad.setText("");
                jTextFieldManoObra.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_jButtonAgregarLineaActionPerformed

    private void jMenuItemEliminarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarLineaActionPerformed
        if(jTableListadoRepuestos.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"NO seleciono nada","AVISO",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            DefaultTableModel modelo = (DefaultTableModel) jTableListadoRepuestos.getModel();
            modelo.removeRow(jTableListadoRepuestos.getSelectedRow());
        }
    }//GEN-LAST:event_jMenuItemEliminarLineaActionPerformed

    private void jButtonAregarListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAregarListadoActionPerformed
        if(jTableListadoRepuestos.getRowCount()==0){
            JOptionPane.showMessageDialog(this,"No se puede guardar un listado vacio","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if(jComboBoxReparacion.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this,"NO selecciono ninguna reparacion","AVISO",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            try {
                conectar.repuestosEnReparaciones(jTableListadoRepuestos,jComboBoxReparacion.getSelectedItem().toString());
                componente.limpiarTabla(jTableListadoRepuestos);
                JOptionPane.showMessageDialog(this,"El Listado de respuestos se agrego a la reparacion "+jComboBoxReparacion.getSelectedItem()
                ,"AVISO",JOptionPane.INFORMATION_MESSAGE);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Mecanicos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonAregarListadoActionPerformed

    private void jButtonMecEnRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMecEnRepActionPerformed
        VerMecanicosPorReparacion MecXrep = new VerMecanicosPorReparacion();
        MecXrep.setVisible(true);
    }//GEN-LAST:event_jButtonMecEnRepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mecanicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mecanicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mecanicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mecanicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mecanicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAgregarLinea;
    private javax.swing.JButton jButtonAgregarMC;
    private javax.swing.JButton jButtonAgregarMCRP;
    private javax.swing.JButton jButtonAregarListado;
    private javax.swing.JButton jButtonMecEnRep;
    private javax.swing.JComboBox<String> jComboBoxMecanicos;
    private javax.swing.JComboBox<String> jComboBoxReparacion;
    private javax.swing.JComboBox<String> jComboBoxReparaciones;
    private javax.swing.JComboBox<String> jComboBoxRepuesto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItemEliminarLinea;
    private javax.swing.JMenuItem jMenuItemEliminarMC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenuListadp;
    private javax.swing.JPopupMenu jPopupMenuMC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableListadoRepuestos;
    private javax.swing.JTable jTableMecanicos;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldCedulaMC;
    private javax.swing.JTextField jTextFieldCienteVH;
    private javax.swing.JTextField jTextFieldCienteVHRE;
    private javax.swing.JTextField jTextFieldManoObra;
    private javax.swing.JTextField jTextFieldNombreMC;
    private javax.swing.JTextField jTextFieldNombreMCR;
    private javax.swing.JTextField jTextFieldNombreRE;
    private javax.swing.JTextField jTextFieldPlacaVH;
    private javax.swing.JTextField jTextFieldPlacaVHRE;
    private javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
