/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import BD.ManejoComponentes;
import Reportes.GenerarReportes;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Jordan Araya
 */
public class TodosDatosReparacion extends javax.swing.JFrame {
    ManejoComponentes componentes = new ManejoComponentes();
    /**
     * Creates new form TodosDatosReparacion
     */
    public TodosDatosReparacion() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setSize(1366, 390);
        componentes.llenarTablas(jTableTodo, jTableTodo.getColumnCount(),
                "SELECT FcNumero,FcCedulaCliente,IfNombreCompleto,VeMatricula,"
                        + "VeMarca,VeModelo,FcFecha,SubTotalColones,SubTotalDolares,"
                        + "TotalColones,TotalDolares FROM Facturacion "
                        + "GROUP BY FcNumero");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTodo = new javax.swing.JTable();
        jButtonReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datos Generales");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Generales"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableTodo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Factura", "Ced. Cliente", "Nombre", "Matricula", "Marca", "Modelo", "Fecha Entrega", "SubTotal CRC", "SubTotal USD", "Total CRC", "Total USD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableTodo);
        if (jTableTodo.getColumnModel().getColumnCount() > 0) {
            jTableTodo.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableTodo.getColumnModel().getColumn(1).setPreferredWidth(75);
            jTableTodo.getColumnModel().getColumn(2).setPreferredWidth(120);
            jTableTodo.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTableTodo.getColumnModel().getColumn(6).setPreferredWidth(100);
            jTableTodo.getColumnModel().getColumn(7).setPreferredWidth(100);
            jTableTodo.getColumnModel().getColumn(8).setPreferredWidth(100);
            jTableTodo.getColumnModel().getColumn(9).setPreferredWidth(100);
            jTableTodo.getColumnModel().getColumn(10).setPreferredWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1330, 275));

        jButtonReporte.setText("Exportar Informacion a PDF");
        jButtonReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 300, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1350, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteActionPerformed
        GenerarReportes reporte = new GenerarReportes();
        try {
            reporte.CrearReporte("TodoReparacion.jasper", "TodosLosDatos.pdf");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TodosDatosReparacion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TodosDatosReparacion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(TodosDatosReparacion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TodosDatosReparacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TodosDatosReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TodosDatosReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TodosDatosReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TodosDatosReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TodosDatosReparacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTodo;
    // End of variables declaration//GEN-END:variables
}
